### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by audi06** [OpenVisionE2/cmdwrapper#1]
@persianpros 
No such file or directory
https://github.com/OpenVisionE2/e2ibox/tree/master/src

```
arm-oe-linux-gnueabi-gcc: error: src/lsdir.c: No such file or directory
arm-oe-linux-gnueabi-gcc: error: src/lsdir.h: No such file or directory
```

https://github.com/e2iplayer/e2ibox/tree/master/src

**Comment by persianpros** [comment]
Thanks for the report, it should be ok now :+1:
